### PR TITLE
Groovy2 integration

### PR DESCRIPTION
**Pull request by edigrid**
Updated groovy version and added needed changes for making smooks to work in an OSGI environment.

### CODE REVIEW

**Comment by ieugen** [comment]
The branch seems to span a long period of time with a lot of commits and seems to be made for merging in 1.5.x maintenance branch instead of master.

**Comment by edigrid** [comment]
I took v1.5.2 tag and made changes on this. Yes, the commit is related to
1.5.x branch, as long as the last release is 1.5.2 and I'm working with
this from what I now.

thanks
Andrei Mura

On Sun, Feb 15, 2015 at 8:10 PM, Ioan Eugen Stan <notifications@github.com>
wrote:

> The branch seems to span a long period of time with a lot of commits and
> seems to be made for merging in 1.5.x maintenance branch instead of master.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smooks/smooks/pull/91#issuecomment-74428791>.
>



-- 
-- 
With kind regards,
Andrei Mura
----------------------------------------------------
EDIGrid GmbH
Pasteurstrasse 42
10407 Berlin
T   +49 30 364286202
M   +49 151 26870264
@   support@edigrid.de
W   www.edigrid.de

Sitz der Gesellschaft Berlin
Registergericht Berlin Charlottenburg HRB 139929
Geschäftsführerin: Andrea König

**Comment by edigrid** [comment]
I took v1.5.2 tag and made changes on this. Yes, the commit is related to 1.5.x branch, as long as the last release is 1.5.2 and I'm working with this from what I now.

**Comment by claudemamo** [comment]
No longer applicable: https://github.com/smooks/smooks-scripting-cartridge/pull/20

**Pull request closed without merging**
